collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0
  brandStrength: 1
  lightness: 0.5232975
  brandColors:
    - '#21201C'
    - '#808A94'
    - '#B2BCC5'
    - '#F3EDCB'
    - '#FE8F61'
  rhythmicContrast: 1
typography_spectrum: 0.1630824
layout_spectrum: 0
name: limbico
