layout_spectrum: 0.2401434
typography_spectrum: 0.1630824
color:
  saturation: 0.8334285
  lightness: 0.5718623
  brandStrength: 0.6684588
  brandColors:
    - '#1B2026'
    - '#EEEDE8'
    - '#7E8A80'
    - '#ACAC9F'
    - '#60605B'
  rhythmicContrast: 0.7841236
name: limbico
