collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.1630824
color:
  saturation: 0.8334285
  brandStrength: 0.5734767
  lightness: 0.3100359
  brandColors:
    - '#21201C'
    - '#808A94'
    - '#B2BCC5'
    - '#F3EDCB'
    - '#FE8F61'
  rhythmicContrast: 0
layout_spectrum: 0.2401434
name: limbico
